name: NuGet.Server CI $(BuildId)

trigger:
  branches:
    include:
    - '*'
  batch: True

variables:
- name: Assemblies
  value: ''
- name: BuildConfiguration
  value: Release
- name: Codeql.Enabled
  value: true
- name: nugetMultiFeedWarnLevel
  value: none
- name: NugetSecurityAnalysisWarningLevel
  value: none
- name: PackageVersion
  value: $(SimplePackageVersion)$(PrereleaseVersion)
- name: PrereleaseVersion
  value: -$(NuGetServerBranch)-$(Build.BuildId)
- name: SimplePackageVersion
  value: 1.0.0
- name: UsePrivateRepo
  value: false
- name: PrivateRepoBranch
  value: main
- name: NuGetServerDirectory
  value: ns
- name: NuGetServerPath
  value: $(Agent.BuildDirectory)\$(NuGetServerDirectory)
- name: ArtifactsFolder
  value: $(NuGetServerPath)\artifacts
- name: NuGetServerBranch
  value: $(Build.SourceBranchName)

resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: NuGet-1ES-Hosted-Pool
      image: NuGet-1ESPT-Win2022
      os: windows
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: stage
      jobs:
      - job: Phase_1
        displayName: Phase 1
        cancelTimeoutInMinutes: 1
        steps:
        - checkout: self
          fetchDepth: 1
          clean: true
          fetchTags: false
          path: $(NuGetServerDirectory)
        - task: PowerShell@1
          name: PowerShell_1
          displayName: Build
          inputs:
            scriptName: $(NuGetServerPath)\build.ps1
            arguments: -Configuration $(BuildConfiguration) -BuildNumber $(Build.BuildId) -SimpleVersion $(SimplePackageVersion) -SemanticVersion $(PackageVersion) -Branch $(NuGetServerBranch) -CommitSHA $(Build.SourceVersion)
            workingFolder: $(NuGetServerPath)
        - task: PowerShell@1
          name: PowerShell_2
          displayName: Run unit tests
          inputs:
            scriptName: $(NuGetServerPath)\test.ps1
            arguments: -Configuration $(BuildConfiguration) -BuildNumber $(Build.BuildId)
            workingFolder: $(NuGetServerPath)
        - task: PublishTestResults@1
          name: PublishTestResults_3
          displayName: Publish Test Results Results.*.xml
          condition: succeededOrFailed()
          inputs:
            testRunner: XUnit
            testResultsFiles: $(NuGetServerPath)\Results.*.xml
